### ISSUE TITLE
【功能请求】Linux 和 MacOS 支持

### ISSUE THREAD

**Issue by taotieren** [aoaoemoji/FiimeFlash#1]
【功能请求】Linux 和 MacOS 支持

**Comment by aoaoemoji** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by aoaoemoji** [comment]
很抱歉现在才看到 不过吧 这个项目已经停止了 现在刷机脚本已经支持 mac和liunx windows了 包含sh的可执行文件
